### ISSUE TITLE
Extra period in citation

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#125]
I was copying the citation info and noticed an extra period after my initials:

``Anderson, S.C., Keppel, E.A., Edwards, A.M.. A reproducible data synopsis ...``

I've tried fixing (and will commit shortly), but haven't built the document for ages (and it didn't work with a quick try) so haven't tested.

Not major but CSAS might notice and come back with it...

**Comment by seananderson** [comment]
Yes, I noticed that recently but haven't looked into it. 

In terms of rebuilding the document, you'll either need to trash all the cached files including the data files (probably easiest to start from scratch with a fresh clone) or I can my cached folders. If you start with a fresh clone you'll at least want to copy over the CPUE cached models since those can take a long time. I can send you those.

**Comment by seananderson** [comment]
Fixed here https://github.com/pbs-assess/csasdown/commit/174213bff313338a7e8781eace251071052405b5
