### ISSUE TITLE
Consider adding a caveats sentence in the abstract

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#96]

**Comment by elisekeppel** [comment]
Perhaps a brief list at the end of the abstract: "This report is not a substitute for stock assessment, and presents data with the following caveats: biomass and catch per unit effort (CPUE) indices require careful interpretation on a stock-by-stock basis to account for species-specific considerations that may not be captured in this synopsis report; commercial CPUE indices are not necessarily proportional to stock abundance due to, among other factors, changes in fisheries management over time; catch history presented here is based on reported data and further species-specific conditions and analysis should be considered and are incorporated into historic catch reconstructions in stock assessments; output in this report is not presented at a spatial scale appropriate for marine spatial planning."

Still under the ~400 word limit for CSAS ResDoc Abstract.

**Comment by seananderson** [comment]
This is going to sound like one of those disclaimer sections at the end of a drug commercial. :)

Let me try editing that down and inserting it in the abstract.

**Comment by seananderson** [comment]
Take a look at what I added here: https://github.com/pbs-assess/gfsynopsis/commit/349aa0474f652ebd6fc14011ba74baa165fc405b
